# Generated by Django 4.2 on 2023-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0002_post_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_link",
            field=models.CharField(default=" ", max_length=225),
        ),
    ]
