# Generated by Django 4.2 on 2023-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0012_profile_campus_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="ticktok_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
