# Generated by Django 4.2 on 2023-06-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0013_profile_github_url_profile_ticktok_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="ticktok_url",
            new_name="tiktok_url",
        ),
    ]
