# Generated by Django 3.2.12 on 2024-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_rename_ticktok_url_profile_tiktok_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tiktok_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Bio', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default_profile.png', null=True, upload_to='images/profile/'),
        ),
    ]
